---
name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git submodule update --init
      - run: cmake .
      - run: cmake --build .
      - run: bin/regress http/https_..
      - run: bin/regress ssl/..
      - run: bin/https-client -url https://kernel.org
