---
name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout-submodules@v1
      - uses: textbook/git-checkout-submodule-action@master
      - name: Build
        run: |
          cmake .
          cmake --build .
