---
name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git submodule update --init
      - run: |
          cmake .
          cmake --build .
